# main parameter file
# YAML is like JSON, but with more minimal syntax and allows comments
# parse.py also adds support for scientific notation in the form: 10^8

debug : true # adds various checks, may cause slow down
verbose : true # prints out more info 
print_lap : 10 # how many laps before another print statement. only if verbose 

parallelism : 10^4 # number of networks to run in parallel (on my desktop 10^5 is the limit with fumia network)
num_samples : 10^5 # number of initial states tested. false to turn off (and use only max_laps instead)
steps_per_lap : 10^3 # number of times to update net in a lap, unless 'lap_stop_rule' is triggered
# note that 'steps_per_lap' is also the assumed transient period for async update methods
update_rule : 'Gasync'  # node update scheme: 'sync', 'async', or 'Gasync' 
# WARNING: async is not efficiently implemented, recommended only to compare with Gasync
# Gasync = "generalized async" where a subset of nodes are sync updated each step 

# implementation details
fraction_per_lap : .9 # fraction of networks needed to satisfy stop condition to exit a lap
clause_bin_size : 4 # number of clauses each threads merges at once
steps_per_lap_gain : 2 # how steps per lap increases as oscillations are not found, set to 1 to turn off

# input
net_file : 'input/fumia.txt' # examples: 'input/fumia.txt', 'input/simpleNet.txt'. See README for syntax description
pheno_file: 'input/fumiaPhenos.yaml' #'input/fumiaPhenos.yaml', 'input/simplePhenos.yaml' if you don't want it, use null or turn use_phenos off
use_phenos : true # quick way to disable phenotypes and ignore pheno_file

# output
output_dir : 'output/'
output_img : 'basinSizes_sync.png'
savefig : 0 # as opposed to showing the image